repos:
- repo: https://github.com/doublify/pre-commit-isort
  rev: v4.3.0
  hooks:
    - id: isort
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-yaml
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: name-tests-test
    - id: requirements-txt-fixer
    - id: sort-simple-yaml
    - id: trailing-whitespace
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.1
  hooks:
    - id: go-fmt
